/* All authoring state stays in the browser unless the local compiler is invoked. */
(() => {
  'use strict';
  const C=window.Tex2HTML,$=id=>document.getElementById(id),E=C.esc;
  const exampleSty=String.raw`% 示例宏：可在“自定义命令”中修改
\newcommand{\bF}{{\mathbb F}}
\newcommand{\mU}{{\mathcal U}}
\newcommand{\on}[1]{\operatorname{#1}}
\newcommand{\mEnd}{\on{\mathcal{E}\mathrm{nd}}}
\DeclareMathOperator{\rank}{rank}
\newtheorem{observation}{观察}
\definecolor{courseblue}{HTML}{2563EB}
`;
  const example=String.raw`\documentclass{beamer}
\title{向量与线性运算}
\begin{document}

\begin{frame}{什么是向量？}
我们熟悉的速度、位移和力，都既有大小，又有方向。
\begin{definition}[几何向量]
具有\blue{大小}和\blue{方向}的量称为向量。
记作 $\vec v=(x,y)\in\bF^2$。
\end{definition}
\pp
\begin{example}
从原点指向点 $(2,1)$ 的向量为
\[\vec v=\begin{pmatrix}2\\1\end{pmatrix}.\]
\end{example}
\end{frame}

\begin{frame}{向量加法}
\begin{theorem}[交换律]
对任意向量 $\vec u,\vec v$，有
\[\vec u+\vec v=\vec v+\vec u.\]
\end{theorem}
\pause
\begin{proof}
由平行四边形法则，两种顺序得到同一条对角线。
\end{proof}
\begin{tikzpicture}
\draw[->,thick,blue] (0,0)--(2,1);
\draw[->,thick,red] (2,1)--(3,3);
\draw[->,thick,purple] (0,0)--(3,3);
\end{tikzpicture}
\end{frame}

\begin{frame}{自定义符号与待处理内容}
递归宏：$\mEnd(\mU)$；算子：$\rank A$。
\begin{observation}
导入样式文件后，自定义数学环境也能统一排版。
\end{observation}
\only<2->{这段 overlay 内容默认显示。}
\mysterycommand{未知内容会原样保留，并出现在警告列表。}
\xymatrix{U \ar[r]^f & V}
\end{frame}
\end{document}
`;
  let state={files:[{name:'example.tex',text:example}],styles:[{name:'example.sty',text:exampleSty}],assets:{},cssText:'',config:{...C.defaults(),frameSelection:{}},model:null,active:'tex:0',page:0,view:'preview',ruleTab:'rules',all:true,recent:[],lectureManifest:null},history=[],timer,dialogSave,urls=[],lectureRangeAnchor=null;
  let typesetQueue=Promise.resolve();
  function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error-status',error);}
  function activeFile(){const [kind,index]=state.active.split(':');return (kind==='sty'?state.styles:state.files)[+index];}
  function remember(){if(state.model){history.push(JSON.stringify({model:state.model,config:state.config,files:state.files,styles:state.styles,assets:state.assets,cssText:state.cssText}));if(history.length>12)history.shift();}$('undo').disabled=!history.length;}
  function saveLocal(){try{localStorage.setItem('tex2html-workspace-v1',JSON.stringify({version:1,files:state.files,styles:state.styles,assets:state.assets,cssText:state.cssText,config:state.config,model:state.model,recent:state.recent}));}catch{status('当前浏览器存储空间不足；请点击“保存方案”下载备份。',true);}}
  function safeSVG(source){const doc=new DOMParser().parseFromString(source,'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='svg')throw Error('不是有效 SVG');for(const node of [...doc.querySelectorAll('*')]){if(['script','foreignObject','iframe','object','embed','audio','video','image','a','animate','animateTransform','set'].includes(node.localName)){node.remove();continue;}for(const attr of [...node.attributes]){if(/^on/i.test(attr.name)||(/href$/i.test(attr.name)&&!attr.value.startsWith('#'))||/javascript:|data:|https?:|@import|expression\s*\(/i.test(attr.value))node.removeAttribute(attr.name);}if(node.localName==='style'&&/@import|url\((?!["']?#)|expression/i.test(node.textContent))node.remove();}return new XMLSerializer().serializeToString(doc.documentElement);}
  function safeHTML(html){const template=document.createElement('template');template.innerHTML=html;for(const n of [...template.content.querySelectorAll('*')]){if(['SCRIPT','IFRAME','OBJECT','EMBED','LINK','META','FORM','INPUT','BUTTON','SVG','MATH'].includes(n.tagName)){n.remove();continue;}if(n.tagName==='STYLE'&&/@import|url\(|expression/i.test(n.textContent)){n.remove();continue;}for(const a of [...n.attributes]){if(/^on/i.test(a.name)||a.name==='srcdoc'||(/^(src|href|xlink:href)$/i.test(a.name)&&/^(?:javascript|vbscript|data:text\/html):/i.test(a.value)))n.removeAttribute(a.name);}}return template.innerHTML;}
  function sanitizeModel(model){for(const page of model.pages||[]){C.walkBlocks(page.blocks||[],b=>{if(b.html)b.html=safeHTML(b.html);if(b.svg)b.svg=safeSVG(b.svg);if(b.darkSvg)b.darkSvg=safeSVG(b.darkSvg);if(b.path&&!/^(?:\{\{root\}\})?[^:<>"']+$/.test(b.path))b.path='';});}model.config=C.mergeConfig(model.config);return model;}
  function sanitizeConfig(config){config=C.mergeConfig(config);for(const item of Object.values(config.figure.replacements)){if(item.svg)item.svg=safeSVG(item.svg);if(item.darkSvg)item.darkSvg=safeSVG(item.darkSvg);if(item.path&&!/^(?:\{\{root\}\})?[^:<>"']+$/.test(item.path))item.path='';}return config;}
  function convertAll(record=true){clearTimeout(timer);if(record)remember();const old=state.model;try{const next=C.convert(state.files,state.styles,state.config,state.assets);for(const page of next.pages){const prior=old?.pages.find(p=>p.id===page.id);if(prior?.edited){for(const key of ['title','subtitle','description','number','slug','rules','edited'])page[key]=C.clone(prior[key]??page[key]);}}state.model=next;state.config=next.config;if(!state.cssText)state.cssText=C.pageCSS(state.config,'.tex-converted');state.model.cssText=state.cssText;state.page=Math.min(state.page,Math.max(next.pages.length-1,0));C.refresh(next);renderResult();if(state.ruleTab!=='rules')renderRules();status(`已转换 ${next.frames.length} 个 frame → ${next.pages.length} 页；${allWarnings().filter(w=>w.severity!=='info').length} 条内容待检查。${old?.layoutEdited?'页面编排已按新规则重建，可撤销。':''}`);saveLocal();}catch(e){status('转换失败：'+e.message,true);console.error(e);}}
  function schedule(){if($('auto-preview').checked){clearTimeout(timer);timer=setTimeout(()=>convertAll(false),450);}else status('输入或规则已修改；点击“重新转换全部”更新结果。');}
  function lineNumbers(){const file=activeFile();$('line-numbers').textContent=Array.from({length:(file?.text.match(/\n/g)||[]).length+1},(_,i)=>i+1).join('\n');$('source-info').textContent=`${(file?.text||'').length.toLocaleString()} 字符 · UTF-8`;}
  async function lectureFetch(path,responseType='text'){const response=await fetch('api/lecture-file?path='+encodeURIComponent(path));if(!response.ok)throw Error('读取讲稿文件失败：'+path);return responseType==='blob'?response.blob():response.text();}
  function cleanTexSource(source){return String(source||'').split(/\r?\n/).map(line=>{let out='',escaped=false;for(const ch of line){if(ch==='%'&&!escaped)break;out+=ch;escaped=ch==='\\'&&!escaped;}return out;}).join('\n');}
  function lectureFrames(text){const out=[];const re=/\\begin\s*\{frame\}(?:\s*\[[^\]]*\])?(?:\s*\{([^}]*)\})?/g;let m;while((m=re.exec(text))){const start=m.index,end=text.indexOf('\\end{frame}',re.lastIndex),sourceEnd=end>=0?end+'\\end{frame}'.length:text.length,inner=end>=0?text.slice(re.lastIndex,end):text.slice(re.lastIndex);const embedded=inner.match(/\\frametitle\s*\{([^}]*)\}/);const raw=m[1]||embedded?.[1]||'';out.push({index:out.length,title:raw.replace(/\\[a-zA-Z]+(?:\{([^}]*)\})?/g,'$1').trim()||'未命名 frame',sourceStart:start,sourceEnd});if(end>=0)re.lastIndex=sourceEnd;}return out;}
  function renderLectureFrames(){const summary=$('lecture-frame-summary'),file=state.files.find(f=>f.name===state.lectureManifest?.selectedTex),frames=file?lectureFrames(file.text):[];if(!file){if(summary)summary.textContent='选择 frames';$('lecture-frames').innerHTML='<p class="muted">选 tex 文件</p>';return;}if(!frames.length){if(summary)summary.textContent='选择 frames';$('lecture-frames').innerHTML='<p class="muted">当前文件没有检测到 \\begin{frame}。</p>';return;}const configured=state.config.frameSelection?.[file.name],selected=Array.isArray(configured)?configured:[];if(summary)summary.textContent=selected.length?(frames.find(f=>f.index===selected[0])?.title||'未命名 frame'):'选择 frames';$('lecture-frames').innerHTML=frames.map(f=>`<label class="frame-choice"><input type="checkbox" data-lecture-frame="${f.index}"${selected.includes(f.index)?' checked':''}><span>${f.index+1}. ${E(f.title)}</span></label>`).join('');}
  function lectureHeadingContext(text,position){const re=/\\(section|subsection|subsubsection)\s*(?:\[[^\]]*\])?\s*\{[^{}]*\}/g,latest={};let m;while((m=re.exec(text))&&m.index<position)latest[m[1]]=m[0];return ['section','subsection','subsubsection'].map(k=>latest[k]).filter(Boolean);}
  function highlightTex(source){let html='',i=0;while(i<source.length){const ch=source[i];if(ch==='%'){const end=source.indexOf('\n',i);const stop=end<0?source.length:end;html+=`<span class="tex-token-comment">${E(source.slice(i,stop))}</span>`;i=stop;continue;}if(ch==='\\'){const m=source.slice(i).match(/^\\[A-Za-z@]+[*]?/);const token=m?m[0]:source.slice(i,i+2);html+=`<span class="tex-token-command">${E(token)}</span>`;i+=token.length;continue;}if(ch==='$'){html+=`<span class="tex-token-math">$</span>`;i++;continue;}if('{}[]()'.includes(ch)){html+=`<span class="tex-token-brace">${E(ch)}</span>`;i++;continue;}let j=i+1;while(j<source.length&&!['%','\\','$','{','}','[',']','(',')'].includes(source[j]))j++;html+=E(source.slice(i,j));i=j;}return html;}
  function renderLectureCode(){const preview=$('lecture-tex-preview');if(!preview)return;const file=state.files.find(f=>f.name===state.lectureManifest?.selectedTex);if(!file){preview.textContent='选 tex 文件';return;}const frames=lectureFrames(file.text),selected=state.config.frameSelection?.[file.name];if(!Array.isArray(selected)||!selected.length){preview.textContent='请选择 frames';return;}const chosen=frames.filter(f=>selected.includes(f.index));let previousEnd=0;const chunks=[];for(const frame of chosen){const headings=previousEnd?(()=>{const re=/\\(?:section|subsection|subsubsection)\s*(?:\[[^\]]*\])?\s*\{[^{}]*\}/g;const between=file.text.slice(previousEnd,frame.sourceStart);return [...between.matchAll(re)].map(m=>m[0]);})():lectureHeadingContext(file.text,frame.sourceStart);const prefix=headings.length?headings.join('\n')+'\n\n':'';const body=file.text.slice(frame.sourceStart,frame.sourceEnd).trim().replace(/^\\begin\s*\{frame\}(?:\s*\[[^\]]*\])?\s*/,'').replace(/\s*\\end\s*\{frame\}\s*$/,'');chunks.push(prefix+body);previousEnd=frame.sourceEnd;}preview.innerHTML=highlightTex(cleanLectureTex(chunks.join('\n\n')));}
  function setLectureFrames(selectAll){const file=state.files.find(f=>f.name===state.lectureManifest?.selectedTex);if(!file)return;lectureRangeAnchor=null;const frames=lectureFrames(file.text),selected=selectAll?frames.map(f=>f.index):[];state.config.frameSelection={...(state.config.frameSelection||{}),[file.name]:selected};renderLectureFrames();renderLectureCode();convertAll(false);status(selectAll?`已选择全部 ${frames.length} 个 frame。`:'已清空 frame 选择，当前没有待转换 frame。');}
  async function loadLectureDefaults(){if(!state.lectureManifest)return;try{const styleText=await lectureFetch(state.lectureManifest.style);state.styles=[{name:'_hanhai.sty',text:styleText}];const assets={};for(const relative of state.lectureManifest.pictures||[]){try{const blob=await lectureFetch(relative,'blob');assets[relative.split('/').pop()]={name:relative.split('/').pop(),data:await dataURL(blob)};}catch{}}state.assets=assets;renderFiles();convertAll(false);status(`已加载 _hanhai.sty 与 ${Object.keys(assets).length} 个图片。`);}catch(e){status(e.message,true);}}
  async function loadLectureTex(){const relative=$('lecture-tex-select').value;if(!relative||!state.lectureManifest)return;try{const text=cleanTexSource(await lectureFetch(relative));state.files=[{name:relative.split('/').pop(),text}];state.lectureManifest.selectedTex=relative.split('/').pop();state.active='tex:0';const frames=lectureFrames(text);state.config.frameSelection={[state.files[0].name]:frames.map(f=>f.index)};renderFiles();renderLectureFrames();renderLectureCode();const picker=document.querySelector('.frame-picker');if(picker)picker.open=false;convertAll(false);status(`已加载 ${relative}，已全选 ${frames.length} 个 frame 并完成转换。`);await loadLectureDefaults();}catch(e){status(e.message,true);}}
  async function initLectureSource(){try{const response=await fetch('api/lecture-manifest');if(!response.ok)throw Error('本地讲稿目录服务不可用');const manifest=await response.json();state.lectureManifest=manifest;$('lecture-tex-select').innerHTML='<option value="">选 tex 文件</option>'+manifest.sections.map(p=>`<option value="${E(p)}">${E(p.replace(/^sections\//,'').replace(/\.tex$/i,''))}</option>`).join('');state.files=[{name:'input.tex',text:''}];state.styles=[];state.assets={};state.lectureManifest.selectedTex='';state.config.frameSelection={};state.model=null;state.all=true;state.active='tex:0';const defaultTex=manifest.sections.find(p=>/01\s*vectors\.tex$/i.test(p))||manifest.sections[0];if(defaultTex){$('lecture-tex-select').value=defaultTex;await loadLectureTex();}else{renderFiles();renderLectureFrames();renderLectureCode();convertAll(false);status('选 tex 文件');}}catch(e){$('lecture-tex-select').innerHTML='<option>讲稿目录服务不可用</option>';status('未连接本地讲稿目录：'+e.message,true);}}
  function renderFiles(){const entries=[...state.files.map((f,i)=>({f,key:'tex:'+i})),...state.styles.map((f,i)=>({f,key:'sty:'+i}))];if(!entries.some(e=>e.key===state.active))state.active=entries[0]?.key||'tex:0';$('file-select').innerHTML=entries.map(e=>`<option value="${e.key}">${E(e.f.name)}</option>`).join('');$('file-select').value=state.active;$('tex-input').value=activeFile()?.text||'';lineNumbers();$('file-count').textContent=`(${entries.length} + ${Object.keys(state.assets).length} 图片)`;$('file-list').innerHTML=entries.map(e=>`<p>${E(e.f.name)} <button data-remove-file="${e.key}">移除</button></p>`).join('')+Object.keys(state.assets).map(name=>`<p>图片 · ${E(name)}</p>`).join('');$('recent-files').innerHTML=state.recent.slice(0,6).map(f=>`<p class="muted">最近：${E(f.name)} · ${E(f.date)}</p>`).join('');}
  function get(path){return path.split('.').reduce((a,k)=>a?.[k],state.config);}
  function set(path,value){const keys=path.split('.');let o=state.config;for(const key of keys.slice(0,-1))o=o[key]||(o[key]={});o[keys.at(-1)]=value;}
  function field(label,path,type='text',options){const value=get(path);let input;if(type==='select')input=`<select data-config="${E(path)}">${options.map(([v,t])=>`<option value="${E(v)}"${value===v?' selected':''}>${E(t)}</option>`).join('')}</select>`;else if(type==='textarea')input=`<textarea data-config="${E(path)}">${E(value)}</textarea>`;else input=`<input type="${type}" data-config="${E(path)}" value="${E(value)}"${type==='number'?' step="1" min="0" max="3000"':''}>`;return `<label class="field"><span>${E(label)}</span>${input}</label>`;}
  function check(label,path){return `<label class="check"><input type="checkbox" data-config="${E(path)}"${get(path)?' checked':''}>${E(label)}</label>`;}
  function group(title,body,open=false){return `<details class="rule-group"${open?' open':''}><summary>${title}</summary>${body}</details>`;}
  const pauseOptions=[['ignore','忽略（默认）'],['block','拆成知识块'],['page','拆成知识页面'],['collapse','转换为折叠内容'],['preserve','保留并警告']];
  const visibility=[['show','全部显示'],['hide','隐藏（报告中记录）'],['collapse','折叠内容'],['supplement','标记为补充'],['preserve','保留并警告']];
  function renderRules(){document.querySelectorAll('[data-rule-tab]').forEach(b=>b.classList.toggle('active',b.dataset.ruleTab===state.ruleTab));let html='';
    if(state.ruleTab==='rules'){
      html+=group('页面拆分',`<p class="hint">默认一个 frame 对应一页。目录中可多选合并，预览中可按内容块拆分。</p>${field('\\pp 的处理方式','pp','select',pauseOptions)}${field('\\pause 的处理方式','pause','select',pauseOptions)}${field('按数学环境分页','splitEnvironment','select',[['none','不额外拆分'],...Object.entries(state.config.environments).map(([k,v])=>[k,v.label])])}${field('用户分页命令','separator')}<p class="hint">默认分隔线为 \\lessonbreak。嵌套环境中的分页会显示警告，不破坏环境结构。</p>`,true);
      html+=group('标题、编号与文件名',`<div class="field-row">${field('章节编号','chapter','number')}${field('子节编号','section','number')}</div>${field('起始知识页编号','start','number')}${check('自动编号','autoNumber')}${check('编号显示 §','sectionSign')}${check('正文中显示编号','bodyNumber')}${check('正文中显示页面标题','bodyTitle')}${check('清理标题中的字体与颜色命令','cleanTitle')}${field('副标题','subtitle','select',[['framesubtitle','从 framesubtitle 提取'],['none','不提取']])}${field('页面说明','description','select',[['empty','留空，逐页编辑'],['title','使用页面标题']])}${field('slug 生成方式','slugMode','select',[['number','英文前缀 + 编号'],['chinese','中文标题']])}<p class="hint">英文语义 slug 可在“编辑本页”中填写。独立网页的标题由课程目录生成，默认不重复输出正文标题。</p>`);
      html+=group('Beamer 与模式内容',Object.keys(state.config.beamer).map(name=>field('\\'+name,'beamer.'+name,'select',name==='alt'?[...visibility,['teacher','教师：第一分支'],['student','学生：第二分支']]:visibility)).join('')+'<p class="hint">columns 第一阶段按顺序转为单栏，并记录提示。overlay 默认全部显示。</p>');
      html+=group('TikZ / XY-pic 图形',`<div class="compile-state" id="compile-state">当前为有限 TikZ 支持模式，复杂命令可能需要本地编译。XY-pic 可使用同一本地服务。</div>${field('图形转换方式','figure.engine','select',[['browser','浏览器有限 TikZ 子集'],['local','本地 LaTeX 编译服务']])}${check('转换 TikZ','figure.tikz')}${check('转换 XY-pic','figure.xypic')}${field('本地服务地址','figure.service')}<button id="check-service">检查服务</button> <button id="compile-figures">编译待处理图形</button>${field('SVG 输出目录','figure.directory')}${field('SVG 文件名前缀','figure.prefix')}<div class="field-row">${field('SVG 宽度 px','figure.width','number')}${field('最大宽度 %','figure.maxWidth','number')}</div>${check('透明背景','figure.transparent')}<div class="field-row">${field('明亮背景','figure.background','color')}${field('暗色背景','figure.darkBackground','color')}</div>${check('裁剪空白边缘','figure.crop')}${field('本地编译文字处理','figure.textMode','select',[['path','文字转路径（包含字形）'],['text','保留 SVG 文本（依赖字体）']])}${check('生成明亮版本','figure.light')}${check('生成暗色版本','figure.dark')}${check('自动添加图片说明','figure.caption')}${check('允许横向滚动','figure.scroll')}${check('保持原始宽高比','figure.aspect')}${field('TikZ libraries','figure.libraries')}${field('本地编译前导代码','figure.preamble','textarea')}<p class="hint">浏览器只转换数值坐标折线。复杂图形保留源码，可在“图形”页上传替代 SVG。此处不会自动执行导入的完整 .sty。</p>`);
      html+=group('图片与输出',`${field('导入图片最大宽度 %','image.maxWidth','number')}${check('显示图片说明','image.caption')}${field('警告列表过滤','warningLevel','select',[['all','全部提示'],['warning','仅待处理问题'],['error','仅错误']])}<p class="hint">报告始终包含全部诊断。导出使用 content/chapterXX/sectionXX，资源路径自动采用 {{root}}。</p>${field('未解析命令名称','_unknownName')}<button id="add-unknown">指定转换方式</button>`);
    }else if(state.ruleTab==='macros'){
      html=`<div class="sticky-search"><input id="macro-search" type="search" placeholder="搜索命令、来源或展开内容" aria-label="搜索自定义命令"></div><div class="inline-actions"><button id="add-macro">＋ 添加命令</button><button id="reset-macros">恢复导入值</button></div><p class="muted">标准定义与 \\nc 别名自动识别；条件宏保留原文。</p><div id="macro-list"></div>`;
    }else{
      html+=group('数学环境样式',`${field('选择环境','_styleEnv','select',Object.entries(state.config.environments).map(([k,v])=>[k,v.label+' · '+k]))}<div id="environment-fields"></div>`,true);
      html+=group('颜色命令',`${field('选择颜色命令','_colorName','select',Object.keys(state.config.colors).map(k=>[k,'\\'+k]))}<div id="color-fields"></div><button id="add-color">＋ 添加颜色</button>`,true);
    }
    $('rules-content').innerHTML=html;
    if(state.ruleTab==='macros')renderMacros();if(state.ruleTab==='styles')renderStyleFields();
  }
  function renderStyleFields(){let name=state.config._styleEnv||'theorem';if(!state.config.environments[name])name='theorem';state.config._styleEnv=name;const p='environments.'+name;document.querySelector('[data-config="_styleEnv"]').value=name;$('environment-fields').innerHTML=field('显示名称',p+'.label')+`<div class="field-row">${field('明亮文字',p+'.light','color')}${field('暗色文字',p+'.dark','color')}${field('明亮背景',p+'.background','color')}${field('暗色背景',p+'.darkBackground','color')}${field('明亮左边框',p+'.border','color')}${field('暗色左边框',p+'.darkBorder','color')}</div>`+check('显示编号',p+'.numbered')+check('默认折叠',p+'.collapsed')+check('显示图标',p+'.icon')+`<div class="field-row">${field('标题字号',p+'.headingSize','number')}${field('正文字号',p+'.bodySize','number')}${field('内边距',p+'.padding','number')}${field('圆角',p+'.radius','number')}</div>`+check('打印保留背景',p+'.printBackground');let cn=state.config._colorName||'blue';if(!state.config.colors[cn])cn='blue';state.config._colorName=cn;document.querySelector('[data-config="_colorName"]').value=cn;const cp='colors.'+cn;$('color-fields').innerHTML=field('处理方式',cp+'.mode','select',[['color','保留颜色'],['bold','改为加粗'],['mark','改为重点标记'],['plain','仅保留文字']])+`<div class="field-row">${field('明亮颜色',cp+'.light','color')}${field('暗色颜色',cp+'.dark','color')}</div>`;}
  function renderMacros(filter=''){const entries=Object.entries(state.model?.registry.macros||{}).filter(([name,m])=>(name+' '+m.body+' '+m.source).toLowerCase().includes(filter.toLowerCase()));$('macro-list').innerHTML=entries.slice(0,100).map(([name,m])=>{const uses=C.usages(state.files,name);return `<section class="macro-card"><header><code>\\${E(name)}</code><label class="check"><input type="checkbox" data-macro-enable="${E(name)}"${m.enabled!==false?' checked':''}>启用</label></header><small>${E(m.source)}:${m.line||1} · ${uses.length} 次使用${m.unsafe?' · ⚠ '+E(m.unsafe):''}</small><textarea aria-label="${E(name)} 展开结果" data-macro-body="${E(name)}">${E(m.body)}</textarea><div class="inline-actions"><select aria-label="${E(name)} 展开范围" data-macro-scope="${E(name)}">${[['all','文本和数学'],['math','仅数学模式'],['text','仅普通文本'],['preserve','保留原命令']].map(([v,t])=>`<option value="${v}"${m.scope===v?' selected':''}>${t}</option>`).join('')}</select><button data-macro-reset="${E(name)}">恢复</button><button data-macro-uses="${E(name)}">使用位置</button></div></section>`;}).join('')+(entries.length>100?'<p class="muted">仅显示前 100 个，请搜索缩小范围。</p>':'');}
  function allWarnings(){return [...(state.model?.globalWarnings||[]),...(state.model?.pages||[]).flatMap(p=>p.warnings||[])].filter((w,i,a)=>a.findIndex(v=>v.file===w.file&&v.line===w.line&&v.command===w.command&&v.reason===w.reason)===i);}
  function current(){return state.model?.pages[state.page];}
  function renderResult(){if(!state.model)return;C.refresh(state.model);$('stat-frames').textContent=state.model.frames.length;$('stat-pages').textContent=state.model.pages.length;const count=allWarnings().filter(w=>w.severity!=='info').length;$('stat-warnings').textContent=count;$('warning-badge').textContent=count;$('page-select').innerHTML=state.model.pages.map((p,i)=>`<option value="${i}">${E(p.number)} ${E(p.title)}</option>`).join('');$('page-select').value=String(state.page);$('page-list').innerHTML=state.model.pages.map((p,i)=>`<div class="page-row" draggable="true" data-page-row="${i}"><input type="checkbox" data-page-check="${i}" aria-label="选择 ${E(p.title)}"><span>${E(p.number+' '+p.title)}</span><button data-page-up="${i}" aria-label="上移页面">↑</button><button data-page-down="${i}" aria-label="下移页面">↓</button><button data-page-edit="${i}">编辑</button><button data-page-delete="${i}">删除</button></div>`).join('');$('undo').disabled=!history.length;renderOutput();}
  function blobURL(text,type='image/svg+xml'){const url=URL.createObjectURL(new Blob([text],{type}));urls.push(url);return url;}
  function assetPreview(html,page){const entries=C.exportFiles({...state.model,pages:[page]});for(const entry of entries){if(entry.path.endsWith('.svg')&&entry.text)html=html.split('{{root}}'+entry.path).join(blobURL(safeSVG(entry.text)));else if(entry.data)html=html.split('{{root}}'+entry.path).join(entry.data);}return html.replaceAll('{{root}}','../../');}
  function previewBlocks(page,config){let output='',pending='',policy=page.blocks.some(b=>b.type==='boundary'&&b.policy==='block')?'block':null;
    const flush=()=>{if(!pending)return;output+=policy==='collapse'?`<details class="lesson-step"><summary>显示补充内容</summary>${pending}</details>`:policy==='block'?`<div class="lesson-step">${pending}</div>`:pending;pending='';};
    for(const [i,b] of page.blocks.entries()){if(b.deleted)continue;if(b.type==='boundary'){flush();policy=b.policy;continue;}pending+=`<div class="preview-block" draggable="true" data-block-page="${E(page.id)}" data-block-id="${E(b.id)}" data-block-index="${i}">${assetPreview(C.renderBlock(b,config),page)}<div class="block-actions"><button data-block-action="up" aria-label="上移内容块">↑</button><button data-block-action="down" aria-label="下移内容块">↓</button><button data-block-action="edit">编辑</button><button data-block-action="split">从此处拆分</button><button data-block-action="source">源码</button><button data-block-action="delete">删除</button></div></div>`;}flush();return output;
  }
  function renderOutput(){const output=$('output');for(const url of urls)URL.revokeObjectURL(url);urls=[];window.MathJax?.typesetClear?.([output]);output.replaceChildren();output.dataset.theme=state.config.theme;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===state.view);b.setAttribute('aria-selected',String(b.dataset.view===state.view));});$('theme-light').setAttribute('aria-pressed',String(state.config.theme==='light'));$('theme-dark').setAttribute('aria-pressed',String(state.config.theme==='dark'));$('all-pages').textContent=state.all?'单页预览':'全部预览';const page=current();let html='';
    if(state.view==='preview'){
      const pages=state.all?state.model.pages:page?[page]:[];html=(state.cssText?`<style>${state.cssText}</style>`:'')+pages.map(p=>{const config=C.pageConfig(state.model,p),scope=C.pageScope(p),hierarchy=[p.sectionTitle,p.subsectionTitle].filter(Boolean).join(' / ');return `<article class="preview-page"><header class="preview-heading"><span class="page-number">${E((config.sectionSign?'§':'')+p.number)} / ${E(p.slug)}</span>${hierarchy?`<p class="tex-hierarchy">${E(hierarchy)}</p>`:''}<h2>${E(p.title)}</h2>${p.subtitle?`<p>${E(p.subtitle)}</p>`:''}${p.description?`<p>${E(p.description)}</p>`:''}</header><div class="tex-converted ${scope}">${previewBlocks(p,config)}</div>${p.blocks.some(b=>b.deleted)?`<div class="restore-list muted">已删除：${p.blocks.filter(b=>b.deleted).map(b=>`<button data-restore-block="${b.id}" data-restore-page="${p.id}">恢复 ${E(b.title||b.environment||b.type)}</button>`).join('')}</div>`:''}</article>`;}).join('')||'<div class="empty">在左侧输入 TeX，开始转换。</div>';
    }else if(state.view==='html')html=`<pre class="code-output">${E(page?.html||'')}</pre>`;
    else if(state.view==='css')html=`<div class="css-editor-wrap"><p class="hint">这是导出时使用的共享 CSS。修改后点击保存，之后转换不会自动覆盖它。</p><textarea id="css-editor" class="css-editor" spellcheck="false">${E(state.cssText||'')}</textarea><div class="inline-actions"><button id="save-css" class="primary">保存 CSS</button><button id="download-css">下载 CSS 文件</button><button id="reset-css">恢复自动生成</button></div></div>`;
    else if(state.view==='json')html=`<pre class="code-output">${E(JSON.stringify({section:state.model.section,pages:state.all?state.model.pages:page?[page]:[],globalWarnings:state.model.globalWarnings},null,2))}</pre>`;
    else if(state.view==='log')html=`<pre class="code-output">${E(state.model.log.join('\n'))}</pre>`;
    else if(state.view==='warnings'){const warnings=allWarnings().filter(w=>state.config.warningLevel==='all'||(state.config.warningLevel==='warning'?w.severity!=='info':w.severity==='error'));html=warnings.map(w=>`<div class="warning-card ${w.severity==='info'?'info':''}"><strong>${E(w.file)}:${w.line} · ${E(w.command)}</strong><p>${E(w.reason)}</p><pre>${E(w.raw)}</pre><p>${E(w.suggestion)}</p><button data-warning-jump="${allWarnings().indexOf(w)}">跳转到输入位置</button><button data-warning-edit="${E(w.command)}">手动指定转换方式</button></div>`).join('')||'<div class="empty">当前过滤条件下没有警告。</div>';}
    else if(state.view==='svg'){const figures=state.model.pages.flatMap(p=>p.figures.map(f=>({...f,pageId:p.id}))).filter((f,i,a)=>a.findIndex(x=>x.figureId===f.figureId)===i);html=`<p class="compile-state">${state.config.figure.engine==='local'?'本地服务执行 LaTeX 编译。':'当前为有限 TikZ 支持模式，复杂命令可能需要本地编译。'}</p><button id="compile-from-output">编译待处理图形</button>`+figures.map(f=>{const svg=state.config.theme==='dark'&&f.darkSvg?f.darkSvg:f.svg;return `<section class="figure-card" data-figure="${f.figureId}"><h3>${E(f.caption)} · ${E(f.figureId)}</h3>${svg?`<img src="${blobURL(safeSVG(svg))}" alt="${E(f.caption)}">`:`<p class="muted">${E(f.error)}</p>`}<div class="inline-actions"><button data-figure-upload="${f.figureId}">上传明亮 SVG</button><button data-figure-dark="${f.figureId}">上传暗色 SVG</button><button data-figure-edit="${f.figureId}">路径 / 尺寸 / 说明</button><button data-figure-reset="${f.figureId}">重置图形</button>${svg?`<button data-figure-download="${f.figureId}">下载 SVG</button>`:''}</div><details><summary>原始代码</summary><pre>${E(f.raw)}</pre></details></section>`;}).join('');}
    output.innerHTML=html;if(state.view==='preview')typesetQueue=typesetQueue.catch(()=>{}).then(async()=>{if(window.MathJax?.startup?.promise)await window.MathJax.startup.promise;if(window.MathJax?.typesetPromise)await window.MathJax.typesetPromise([output]);}).catch(e=>status('公式排版提示：'+e.message,true));
  }
  // Generated UI buttons are trusted. Only sanitize externally imported HTML, not the workbench controls.
  function modal(title,html,onSave){$('dialog-title').textContent=title;$('dialog-body').innerHTML=html;dialogSave=onSave;$('edit-dialog').showModal();}
  function input(label,id,value,type='text'){return `<label class="field"><span>${E(label)}</span>${type==='textarea'?`<textarea id="${id}">${E(value)}</textarea>`:`<input id="${id}" type="${type}" value="${E(value)}">`}</label>`;}
  function mutate(fn){remember();fn();state.model.config=state.config;C.refresh(state.model);renderResult();saveLocal();}
  function renumber(){if(state.config.autoNumber)state.model.pages.forEach((p,i)=>p.number=`${state.config.chapter}.${state.config.section}.${+state.config.start+i}`);}
  function editPage(index=state.page){const p=state.model.pages[index];if(!p)return;modal('编辑知识页',input('页面标题','edit-title',p.title)+input('副标题','edit-subtitle',p.subtitle)+input('页面说明','edit-description',p.description,'textarea')+`<div class="field-row">${input('页面编号','edit-number',p.number)}${input('文件 slug','edit-slug',p.slug)}</div>`+`<label class="field"><span>本页证明默认状态</span><select id="edit-proof"><option value="inherit">跟随全局规则</option value="closed">折叠</option><option value="open">展开</option></select></label><label class="check"><input id="edit-body-title" type="checkbox"${C.pageConfig(state.model,p).bodyTitle?' checked':''}>本页正文显示标题</label><p class="muted">仅本页规则保存在方案中，不影响其他页面。</p>`,()=>mutate(()=>{p.title=$('edit-title').value;p.subtitle=$('edit-subtitle').value;p.description=$('edit-description').value;p.number=$('edit-number').value;p.slug=C.safeName($('edit-slug').value);p.edited=true;p.rules.bodyTitle=$('edit-body-title').checked;const proof=$('edit-proof').value;if(proof==='inherit')delete p.rules.environments;else p.rules.environments={...C.clone(state.config.environments),proof:{...state.config.environments.proof,collapsed:proof==='closed'}};}));$('edit-proof').value=p.rules.environments?.proof?(p.rules.environments.proof.collapsed?'closed':'open'):'inherit';}
  function editBlock(page,b){const env=!!b.environment;let html=env?`<label class="field"><span>数学环境类型</span><select id="block-env">${Object.entries(state.config.environments).map(([k,e])=>`<option value="${E(k)}"${k===b.environment?' selected':''}>${E(e.label)}</option>`).join('')}</select></label>${input('数学环境标题','block-title',b.title)}<label class="check"><input id="block-collapsed" type="checkbox"${(b.collapsed??state.config.environments[b.environment].collapsed)?' checked':''}>折叠此块</label>`:'';html+=input('此块 TeX（修改后只重新转换这一块）','block-raw',b.raw,'textarea');html+=`<label class="field"><span>移动到页面</span><select id="block-destination">${state.model.pages.map(p=>`<option value="${E(p.id)}"${p.id===page.id?' selected':''}>${E(p.title)}</option>`).join('')}</select></label>`;modal('编辑内容块',html,()=>mutate(()=>{if($('block-raw').value!==b.raw){const next=C.convert([{name:b.file,text:$('block-raw').value}],state.styles,state.config,state.assets);const newBlocks=next.pages.flatMap(p=>p.blocks);page.blocks.splice(page.blocks.indexOf(b),1,...newBlocks.map((n,i)=>({...n,id:b.id+'-edit-'+i,sourceStart:b.sourceStart,sourceEnd:b.sourceEnd,sourceStartLine:b.sourceStartLine,sourceEndLine:b.sourceEndLine})));page.warnings.push(...next.globalWarnings,...next.pages.flatMap(p=>p.warnings));}else{if(env){b.environment=$('block-env').value;b.type=b.environment;b.title=$('block-title').value;b.collapsed=$('block-collapsed').checked;}const dest=state.model.pages.find(p=>p.id===$('block-destination').value);if(dest&&dest!==page){page.blocks.splice(page.blocks.indexOf(b),1);dest.blocks.push(b);}}state.model.layoutEdited=true;}));}
  function jump(file,offset){let i=state.files.findIndex(f=>f.name===file),kind='tex';if(i<0){i=state.styles.findIndex(f=>f.name===file);kind='sty';}if(i<0)return;state.active=kind+':'+i;renderFiles();const input=$('tex-input');input.focus();input.setSelectionRange(offset,Math.min(input.value.length,offset+50));input.scrollTop=(input.value.slice(0,offset).match(/\n/g)||[]).length*22-100;$('line-numbers').scrollTop=input.scrollTop;}
  function unknownRule(name){name=String(name||'').replace(/^\\/,'');modal('手动转换规则 · \\'+name,input('命令或环境名称','unknown-name',name)+`<label class="field"><span>转换方式</span><select id="unknown-mode"><option value="text">替换为安全的普通文本</option><option value="unwrap">保留参数 / 环境正文</option><option value="preserve">保留原文与警告</option></select></label>`+input('替换文本','unknown-text',state.config.unknown[name]?.value||'','textarea'),()=>{remember();const key=$('unknown-name').value.trim().replace(/^\\/,'');if(!/^[A-Za-z@][A-Za-z@*]*$/.test(key))throw Error('请填写有效命令或环境名称');if($('unknown-mode').value==='preserve')delete state.config.unknown[key];else state.config.unknown[key]={mode:$('unknown-mode').value,value:$('unknown-text').value};convertAll(false);});}
  function choose(accept,multiple,handler){const picker=$('file-picker');picker.accept=accept;picker.multiple=multiple;picker.value='';picker.onchange=async()=>{try{await handler([...picker.files]);}catch(e){status(e.message,true);}};picker.click();}
  async function importText(kind){choose(kind==='sty'?'.sty':'.tex',true,async files=>{remember();for(const f of files){const text=await f.text();if(text.length>2000000)throw Error('单个文件请控制在 2 MB 以内');const list=kind==='sty'?state.styles:state.files,index=list.findIndex(x=>x.name===f.name);if(index>=0)list[index]={name:f.name,text};else list.push({name:f.name,text});state.recent.unshift({name:f.name,date:new Date().toLocaleDateString()});state.active=kind+':'+(index<0?list.length-1:index);}state.recent=state.recent.slice(0,15);renderFiles();convertAll(false);});}
  const dataURL=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});
  function download(name,data,type='application/json'){const url=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.hidden=true;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status('已发起下载：'+name+'；若内嵌浏览器未保存文件，请在 Edge / Chrome 中打开本工具。');}
  function cleanLectureTex(source){return cleanTexSource(source).replace(/\n{3,}/g,'\n\n').trim()+'\n';}
  async function preparedEntries(){return Promise.all(C.exportFiles(state.model).map(async e=>({...e,bytes:e.data?new Uint8Array(await(await fetch(e.data)).arrayBuffer()):undefined})));}
  async function exportZip(filter){if(!state.model)return;const entries=(await preparedEntries()).filter(filter||(()=>true)).map(e=>({...e,path:'converted/'+e.path}));download('converted.zip',TexZip.zip(entries));status(`已导出 ${entries.length} 个文件；新增页面请按 manifest 登记到课程目录。`);}
  function findFigure(id){return state.model.pages.flatMap(p=>p.figures).find(f=>f.figureId===id);}
  function applyFigure(id,replacement){state.config.figure.replacements[id]={...state.config.figure.replacements[id],...replacement};for(const page of state.model.pages)C.walkBlocks(page.blocks,b=>{if(b.figureId===id){Object.assign(b,replacement,{error:''});page.warnings=page.warnings.filter(w=>!(w.offset===b.sourceStart&&/TikZ|XY-pic|本地|图形|SVG|坐标|路径/.test(w.reason)));}});state.model.config=state.config;C.refresh(state.model);}
  function uploadFigure(id,dark=false){choose('.svg,image/svg+xml',false,async files=>{if(!files[0])return;const svg=safeSVG(await files[0].text());mutate(()=>applyFigure(id,dark?{darkSvg:svg}:{svg}));});}
  function figureOptions(id){const f=findFigure(id);modal('图形路径、尺寸与说明',input('站内 SVG 路径（可使用 {{root}}）','figure-path',f.path||'')+input('SVG 宽度 px','figure-width',f.width||640,'number')+input('图片说明','figure-caption',f.caption),()=>{const path=$('figure-path').value;if(path&&!/^(?:\{\{root\}\})?[^:<>"']+\.svg$/i.test(path))throw Error('请使用站内 .svg 路径');mutate(()=>applyFigure(id,{path,width:Math.max(80,Math.min(3000,+$('figure-width').value||640)),caption:$('figure-caption').value}));});}
  function localURL(path){const url=new URL(state.config.figure.service);if(!['127.0.0.1','localhost','[::1]'].includes(url.hostname))throw Error('图形服务仅允许本机地址');return new URL(path,url).href;}
  async function checkService(){try{const r=await fetch(localURL('/health'),{signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('HTTP '+r.status);const data=await r.json();const message=`本地服务已连接 · ${data.engine} · dvisvgm ${data.dvisvgm?'可用':'缺失'}`;if($('compile-state'))$('compile-state').textContent=message;status(message);}catch(e){status('本地服务未连接。运行 node tools/tex2html/server.js 后重试。'+e.message,true);}}
  async function compileFigures(){if(!state.model)return;const figures=state.model.pages.flatMap(p=>p.figures).filter((f,i,a)=>!f.svg&&a.findIndex(x=>x.figureId===f.figureId)===i);if(!figures.length){status('没有待编译的图形。');return;}let token;try{const r=await fetch(localURL('/health'),{signal:AbortSignal.timeout(6000)});const health=await r.json();if(!health.ok)throw Error('本地 xelatex 或 dvisvgm 不可用');token=health.token;}catch(e){status('无法连接本地编译服务：'+e.message,true);return;}remember();let done=0;for(const f of figures){try{status(`本地编译 ${++done}/${figures.length}：${f.figureId}`);const source=C.expand(f.raw,state.model.registry.macros,'math',()=>{}).replace(/\\(?:pp|pause)\b/g,'');const r=await fetch(localURL('/convert/'+(f.kind==='tikz'?'tikz':'xypic')),{method:'POST',headers:{'Content-Type':'application/json','X-Tex2HTML-Token':token},body:JSON.stringify({source,options:state.config.figure}),signal:AbortSignal.timeout(150000)});const result=await r.json();if(!r.ok)throw Error(result.error+(result.log?'\n'+result.log:''));applyFigure(f.figureId,{svg:safeSVG(result.svg),darkSvg:result.darkSvg?safeSVG(result.darkSvg):null});state.model.log.push(...(result.warnings||[]),`已编译 ${f.figureId}`);}catch(e){state.model.log.push(`${f.figureId} 编译失败：${e.message}`);for(const page of state.model.pages){if(page.figures.some(x=>x.figureId===f.figureId))page.warnings.push({file:f.file,line:f.sourceStartLine,offset:f.sourceStart,command:f.kind,raw:f.raw,reason:e.message,suggestion:'查看日志，或上传已生成的 SVG。',severity:'error'});}}renderResult();}saveLocal();status('图形编译结束。失败项保留源码，可在警告和日志中查看原因。');}
  function addMacro(){modal('添加自定义命令',input('名称（不含反斜杠）','macro-name','')+input('参数个数（0–9）','macro-args',0,'number')+input('展开结果（使用 #1、#2 表示参数）','macro-value','','textarea'),()=>{const name=$('macro-name').value.replace(/^\\/,'').trim();if(!/^[A-Za-z@]+$/.test(name))throw Error('命令名称只能包含英文字母或 @');remember();state.config.macros[name]={name,body:$('macro-value').value,defaultBody:$('macro-value').value,args:Math.max(0,Math.min(9,+$('macro-args').value||0)),optional:null,enabled:true,scope:'all',source:'手动规则',line:1,unsafe:''};convertAll(false);});}
  function importJSON(kind){choose('.json,application/json',false,async files=>{if(!files[0])return;const text=await files[0].text();if(text.length>25000000)throw Error('方案文件过大');const data=JSON.parse(text);remember();if(kind==='config'){state.config=sanitizeConfig(data.config||data);convertAll(false);}else{if(data.version!==1||!Array.isArray(data.files)||!data.files.every(f=>typeof f.name==='string'&&typeof f.text==='string'))throw Error('不是版本 1 的转换方案');state.files=data.files;state.styles=data.styles||[];state.assets=data.assets||{};state.cssText=data.cssText||'';state.config=sanitizeConfig(data.config);state.model=data.model?sanitizeModel(data.model):null;state.active='tex:0';state.page=0;if(state.model){state.model.config=state.config;renderResult();}else convertAll(false);}renderFiles();renderRules();saveLocal();status('已导入并恢复。');});}
  async function writeDirectory(){if(!window.showDirectoryPicker){status('此浏览器不支持目录写入；请使用 ZIP 导出后解压。',true);return;}const entries=await preparedEntries();const handle=await window.showDirectoryPicker({mode:'readwrite'}),collisions=[];for(const e of entries){const segments=e.path.split('/');let dir=handle;try{for(const part of segments.slice(0,-1))dir=await dir.getDirectoryHandle(part);await dir.getFileHandle(segments.at(-1));collisions.push(e.path);}catch(err){if(err.name!=='NotFoundError')throw err;}}const write=async()=>{let count=0;try{for(const e of entries){const parts=e.path.split('/');let dir=handle;for(const part of parts.slice(0,-1))dir=await dir.getDirectoryHandle(part,{create:true});const file=await dir.getFileHandle(parts.at(-1),{create:true}),stream=await file.createWritable();await stream.write(e.bytes||e.text||'');await stream.close();count++;}status(`已写入 ${count} 个文件。新增 slug 仍需登记到课程目录。`);}catch(e){status(`已写入 ${count} 个文件，其余失败：${e.message}`,true);}};if(collisions.length)modal('确认覆盖已有文件',`<p>所选目录中以下 ${collisions.length} 个文件已存在：</p><pre class="code-output">${E(collisions.join('\n'))}</pre><p>保存将覆盖这些文件。</p>`,write);else await write();}
  $('tex-input').addEventListener('input',()=>{if(activeFile())activeFile().text=$('tex-input').value;lineNumbers();schedule();});$('tex-input').addEventListener('scroll',()=>{$('line-numbers').scrollTop=$('tex-input').scrollTop;});$('file-select').onchange=e=>{state.active=e.target.value;renderFiles();};$('import-tex').onclick=()=>importText('tex');$('import-sty').onclick=()=>importText('sty');$('import-images').onclick=()=>choose('image/png,image/jpeg,image/gif,image/webp,image/svg+xml',true,async files=>{remember();for(const f of files){if(f.size>10000000)throw Error('单张图片请控制在 10 MB 以内');let data;if(f.name.endsWith('.svg'))data='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(safeSVG(await f.text()));else data=await dataURL(f);state.assets[f.name]={name:f.name,data};}renderFiles();convertAll(false);});
  $('lecture-tex-select').onchange=()=>{lectureRangeAnchor=null;loadLectureTex();};$('lecture-frames').addEventListener('change',e=>{const input=e.target.closest('[data-lecture-frame]'),file=activeFile();if(!input||!file)return;const frames=lectureFrames(file.text),clicked=+input.dataset.lectureFrame;let selected,completed=false;if(lectureRangeAnchor===null){lectureRangeAnchor=clicked;selected=[clicked];status(`已选起点：第 ${clicked+1} 个 frame；请再点击终点。`);}else{const from=Math.min(lectureRangeAnchor,clicked),to=Math.max(lectureRangeAnchor,clicked);selected=frames.filter(f=>f.index>=from&&f.index<=to).map(f=>f.index);lectureRangeAnchor=null;completed=true;status(`已选择第 ${from+1}–${to+1} 个 frame。`);}state.config.frameSelection={...(state.config.frameSelection||{}),[file.name]:selected};renderLectureFrames();renderLectureCode();convertAll(false);if(completed){const picker=document.querySelector('.frame-picker');if(picker)setTimeout(()=>{picker.open=false;},1000);}});
  $('paste-tex').onclick=async()=>{try{const text=await navigator.clipboard.readText();const input=$('tex-input');input.setRangeText(text,input.selectionStart,input.selectionEnd,'end');input.dispatchEvent(new Event('input'));}catch{status('浏览器未授予剪贴板读取权限；可直接在输入框按 Ctrl+V。',true);}};
  $('clear-tex').onclick=()=>{remember();if(activeFile())activeFile().text='';renderFiles();convertAll(false);};const restoreExample=$('restore-example');if(restoreExample)restoreExample.onclick=()=>{remember();state.files=[{name:'example.tex',text:example}];state.styles=[{name:'example.sty',text:exampleSty}];state.active='tex:0';renderFiles();convertAll(false);};
  $('find-source').onclick=()=>{const input=$('tex-input'),term=$('source-search').value;if(!term)return;let start=input.value.indexOf(term,input.selectionEnd);if(start<0)start=input.value.indexOf(term);if(start<0){status('未找到：'+term);return;}jump(activeFile().name,start);input.setSelectionRange(start,start+term.length);};$('source-search').onkeydown=e=>{if(e.key==='Enter')$('find-source').click();};
  function insertMarkers(selection){if(state.active.startsWith('sty')){status('请先选择 TeX 文件。',true);return;}remember();const input=$('tex-input'),a=input.selectionStart,b=input.selectionEnd,marker='\n'+state.config.separator+'\n';if(selection&&a===b){status('请在输入框中选择需要独立成页的内容。',true);return;}input.setRangeText(selection?marker+input.value.slice(a,b)+marker:marker,a,b,'end');activeFile().text=input.value;lineNumbers();convertAll(false);}
  $('insert-break').onclick=()=>insertMarkers(false);$('selection-page').onclick=()=>insertMarkers(true);$('convert-all').onclick=()=>convertAll();$('auto-preview').onchange=()=>{if($('auto-preview').checked)convertAll();};$('toggle-rules').onclick=()=>{const panel=document.querySelector('.rules-panel'),button=$('toggle-rules'),collapsed=panel.classList.toggle('rules-panel-collapsed');button.setAttribute('aria-expanded',String(!collapsed));button.textContent=collapsed?'展开':'折叠';};$('reset-rules').onclick=()=>{remember();state.config=C.defaults();renderRules();convertAll(false);};
  $('rules-content').addEventListener('input',e=>{if(e.target.id==='macro-search')renderMacros(e.target.value);});
  $('rules-content').addEventListener('change',e=>{const t=e.target,path=t.dataset.config;if(path){if(path.startsWith('_')){set(path,t.value);if(state.ruleTab==='styles')renderStyleFields();return;}remember();set(path,t.type==='checkbox'?t.checked:t.type==='number'?Number(t.value):t.value);if(path.startsWith('environments.')||path==='theme'||path==='warningLevel'||path.startsWith('image.')||['figure.service','figure.preamble','figure.libraries','figure.textMode','figure.directory','figure.prefix','figure.caption','figure.scroll','figure.aspect','figure.maxWidth','figure.light','figure.dark'].includes(path)){state.model.config=state.config;renderResult();saveLocal();}else schedule();}const name=t.dataset.macroBody||t.dataset.macroEnable||t.dataset.macroScope;if(name){remember();const macro=C.clone(state.model.registry.macros[name]);if(t.dataset.macroBody){macro.body=t.value;macro.unsafe='';}if(t.dataset.macroEnable)macro.enabled=t.checked;if(t.dataset.macroScope)macro.scope=t.value;state.config.macros[name]=macro;schedule();}});
  $('rules-content').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;try{if(b.id==='add-macro')addMacro();if(b.id==='reset-macros'){remember();state.config.macros={};convertAll(false);}if(b.dataset.macroReset){remember();delete state.config.macros[b.dataset.macroReset];convertAll(false);}if(b.dataset.macroUses){const usages=C.usages(state.files,b.dataset.macroUses);modal('命令使用位置',usages.map((u,i)=>`<p><button type="button" data-usage-jump="${i}">${E(u.file)}:${u.line}</button></p>`).join('')||'<p>未使用</p>',()=>{});$('dialog-body').onclick=e=>{const b=e.target.closest('[data-usage-jump]');if(b){const u=usages[+b.dataset.usageJump];$('edit-dialog').close();jump(u.file,u.offset);}};}if(b.id==='check-service')checkService();if(b.id==='compile-figures')compileFigures();if(b.id==='add-unknown')unknownRule(state.config._unknownName||'');if(b.id==='add-color')modal('添加颜色',input('颜色名称','new-color-name','')+input('明亮颜色','new-color-light','#2563eb','color')+input('暗色颜色','new-color-dark','#93c5fd','color'),()=>{const name=C.safeName($('new-color-name').value);remember();state.config.colors[name]={light:$('new-color-light').value,dark:$('new-color-dark').value,mode:'color'};state.config._colorName=name;convertAll(false);renderRules();});}catch(err){status(err.message,true);}});
  document.querySelectorAll('[data-rule-tab]').forEach(b=>b.onclick=()=>{state.ruleTab=b.dataset.ruleTab;renderRules();});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;renderOutput();});$('page-select').onchange=e=>{state.page=+e.target.value;state.all=false;renderOutput();};$('all-pages').onclick=()=>{state.all=!state.all;renderOutput();};
  for(const theme of ['light','dark'])$('theme-'+theme).onclick=()=>{state.config.theme=theme;state.model.config.theme=theme;renderOutput();saveLocal();};document.querySelectorAll('.code-theme-toggle [data-code-theme]').forEach(button=>button.onclick=()=>{const theme=button.dataset.codeTheme,box=document.querySelector('.lecture-code-preview');if(!box)return;box.dataset.codeTheme=theme;document.querySelectorAll('.code-theme-toggle [data-code-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));});
  $('edit-page').onclick=()=>editPage();$('undo').onclick=()=>{const item=history.pop();if(!item)return;Object.assign(state,JSON.parse(item));state.page=Math.min(state.page,state.model.pages.length-1);renderFiles();renderRules();renderResult();saveLocal();status('已撤销最近一次操作。');};
  $('page-list').onclick=e=>{const b=e.target.closest('button');if(!b)return;const index=+(b.dataset.pageDelete??b.dataset.pageEdit??b.dataset.pageUp??b.dataset.pageDown);if(b.dataset.pageDelete!==undefined){mutate(()=>{state.model.pages.splice(index,1);state.page=Math.min(state.page,Math.max(state.model.pages.length-1,0));state.model.layoutEdited=true;renumber();});return;}if(b.dataset.pageEdit!==undefined)editPage(index);else{const to=index+(b.dataset.pageUp!==undefined?-1:1);if(to<0||to>=state.model.pages.length)return;mutate(()=>{const [p]=state.model.pages.splice(index,1);state.model.pages.splice(to,0,p);state.page=to;state.model.layoutEdited=true;renumber();});}};
  $('merge-pages').onclick=()=>{const selected=[...document.querySelectorAll('[data-page-check]:checked')].map(n=>+n.dataset.pageCheck);if(selected.length<2){status('请在页面目录中至少选择两页。',true);return;}mutate(()=>{const pages=selected.map(i=>state.model.pages[i]),first=pages[0];first.blocks=pages.flatMap(p=>[...($('keep-titles').checked?[{id:'heading-'+p.id,type:'text',html:'<h3>'+E(p.title)+'</h3>',raw:p.title}]:[]),...p.blocks]);first.sourceFrames=[...new Set(pages.flatMap(p=>p.sourceFrames))];first.warnings=pages.flatMap(p=>p.warnings);first.edited=true;state.model.pages=state.model.pages.filter((p,i)=>i===selected[0]||!selected.includes(i));state.page=selected[0];state.model.layoutEdited=true;renumber();});editPage();};
  let cssSaveTimer;
  $('output').addEventListener('input',e=>{if(e.target.id!=='css-editor')return;state.cssText=e.target.value;state.model.cssText=state.cssText;clearTimeout(cssSaveTimer);cssSaveTimer=setTimeout(()=>{saveLocal();status('共享 CSS 已自动保存。');},400);});  $('output').onclick=e=>{const button=e.target.closest('button');if(!button)return;if(button.id==='download-css'){download('tex2html.css',state.cssText||'', 'text/css;charset=utf-8');return;}if(button.id==='save-css'){ state.cssText=$('css-editor').value;state.model.cssText=state.cssText;saveLocal();renderOutput();status('共享 CSS 已保存。');return;}if(button.id==='reset-css'){if(!window.confirm('恢复自动生成会覆盖当前手动修改的 CSS，确定继续吗？'))return;state.cssText=C.pageCSS(state.config,'.tex-converted');state.model.cssText=state.cssText;saveLocal();renderOutput();status('共享 CSS 已恢复为自动生成版本。');return;}const action=button.dataset.blockAction;if(action){const row=button.closest('[data-block-id]'),page=state.model.pages.find(p=>p.id===row.dataset.blockPage),index=+row.dataset.blockIndex,b=page.blocks[index];if(action==='source'){jump(b.file,b.sourceStart||0);return;}if(action==='edit'){editBlock(page,b);return;}mutate(()=>{if(action==='delete')b.deleted=true;else if(action==='split'){if(index===0)throw Error('请从第二个内容块开始拆分');const id=page.id+'-split-'+Date.now(),next={...C.clone(page),id,title:page.title+'（续）',slug:page.slug+'-part',blocks:page.blocks.splice(index),edited:true};state.model.pages.splice(state.model.pages.indexOf(page)+1,0,next);renumber();}else{const to=index+(action==='up'?-1:1);if(to>=0&&to<page.blocks.length)[page.blocks[index],page.blocks[to]]=[page.blocks[to],page.blocks[index]];}state.model.layoutEdited=true;});}
    if(button.dataset.restoreBlock)mutate(()=>{const p=state.model.pages.find(p=>p.id===button.dataset.restorePage);p.blocks.find(b=>b.id===button.dataset.restoreBlock).deleted=false;});
    if(button.dataset.warningJump!==undefined){const w=allWarnings()[+button.dataset.warningJump];jump(w.file,w.offset||0);}if(button.dataset.warningEdit)unknownRule(button.dataset.warningEdit);
    if(button.dataset.figureUpload)uploadFigure(button.dataset.figureUpload);if(button.dataset.figureDark)uploadFigure(button.dataset.figureDark,true);if(button.dataset.figureEdit)figureOptions(button.dataset.figureEdit);if(button.dataset.figureReset)mutate(()=>{const id=button.dataset.figureReset;delete state.config.figure.replacements[id];for(const page of state.model.pages)C.walkBlocks(page.blocks,b=>{if(b.figureId===id){b.svg=null;b.darkSvg=null;b.path='';b.error='已重置图形，请重新转换或编译';}});});if(button.dataset.figureDownload){const f=findFigure(button.dataset.figureDownload);download(f.figureId+'.svg',state.config.theme==='dark'&&f.darkSvg?f.darkSvg:f.svg,'image/svg+xml');}if(button.id==='compile-from-output')compileFigures();};
  $('reconvert-page').onclick=()=>{const p=current();if(!p)return;const next=C.convert(state.files,state.styles,C.pageConfig(state.model,p),state.assets),matches=next.pages.filter(n=>n.sourceFrames.some(id=>p.sourceFrames.includes(id)));mutate(()=>{p.blocks=matches.flatMap(n=>n.blocks);p.warnings=matches.flatMap(n=>n.warnings);});status('已按本页来源 frame 重新转换；此 frame 的手动拆分边界已重置。');};
  $('copy-page').onclick=async()=>{try{await navigator.clipboard.writeText(current()?.html||'');status('已复制 HTML 正文片段。');}catch{status('剪贴板不可用；切换 HTML 标签手动复制。',true);}};$('download-page').onclick=()=>{const p=current();if(p)download(p.slug+'.html',p.html,'text/html;charset=utf-8');};$('export-zip').onclick=()=>exportZip().catch(e=>status(e.message,true));
   $('save-plan').onclick=()=>download('tex2html-plan.json',JSON.stringify({version:1,files:state.files,styles:state.styles,assets:state.assets,cssText:state.cssText,config:state.config,model:state.model},null,2));$('import-plan').onclick=()=>importJSON('plan');
  $('export-type').onchange=async e=>{const value=e.target.value;e.target.value='';try{if(value==='html')await exportZip(e=>e.path.endsWith('.html'));if(value==='svg')await exportZip(e=>e.path.endsWith('.svg'));if(value==='json')download('conversion.json',JSON.stringify(state.model,null,2));if(value==='report')download('conversion-report.json',JSON.stringify({warnings:allWarnings(),log:state.model.log},null,2));if(value==='config')download('conversion-config.json',JSON.stringify(state.config,null,2));if(value==='import-config')importJSON('config');if(value==='directory')await writeDirectory();}catch(err){status(err.message,true);}};
  $('edit-dialog').addEventListener('close',()=>{$('dialog-body').onclick=null;});$('dialog-save').onclick=async e=>{e.preventDefault();try{await dialogSave?.();$('edit-dialog').close();}catch(err){status(err.message,true);}};
  $('file-list').onclick=e=>{const button=e.target.closest('[data-remove-file]');if(!button)return;remember();const [kind,i]=button.dataset.removeFile.split(':');(kind==='sty'?state.styles:state.files).splice(+i,1);if(!state.files.length)state.files.push({name:'input.tex',text:''});renderFiles();convertAll(false);};
  let dragged=null;document.addEventListener('dragstart',e=>{const block=e.target.closest('[data-block-id]'),page=e.target.closest('[data-page-row]');dragged=block?{kind:'block',page:block.dataset.blockPage,index:+block.dataset.blockIndex}:page?{kind:'page',index:+page.dataset.pageRow}:null;if(dragged)e.dataTransfer.setData('text/plain',JSON.stringify(dragged));});document.addEventListener('dragover',e=>{if(dragged&&e.target.closest('[data-block-id],[data-page-row]'))e.preventDefault();});document.addEventListener('drop',e=>{if(!dragged)return;const block=e.target.closest('[data-block-id]'),page=e.target.closest('[data-page-row]');e.preventDefault();const from=dragged;dragged=null;if(from.kind==='page'&&page)mutate(()=>{const [p]=state.model.pages.splice(from.index,1);state.model.pages.splice(+page.dataset.pageRow,0,p);state.model.layoutEdited=true;renumber();});else if(from.kind==='block'&&block)mutate(()=>{const origin=state.model.pages.find(p=>p.id===from.page),target=state.model.pages.find(p=>p.id===block.dataset.blockPage);const [b]=origin.blocks.splice(from.index,1);target.blocks.splice(+block.dataset.blockIndex,0,b);state.model.layoutEdited=true;});});document.addEventListener('dragend',()=>{dragged=null;});
  try{const saved=JSON.parse(localStorage.getItem('tex2html-workspace-v1')||'null');if(saved?.version===1&&Array.isArray(saved.files)){state={...state,...saved,config:sanitizeConfig(saved.config),model:saved.model?sanitizeModel(saved.model):null};}}catch{status('本地方案无法恢复，已载入示例。',true);}
  renderFiles();renderRules();if(state.model)renderResult();else convertAll(false);initLectureSource();
})();
